### ISSUE TITLE
An error occurs when trying to transfer data from the Redis Source [mode: stream] to the Vitess Destination 

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-redis#23]
### Bug description

The user creates the Redis Souce connector [mode: stream]  and the Vitess Destination connector; then the user starts the pipeline -> the system returns an error

```
2022-10-04T15:52:48+00:00 ERR error writing record error="insert record: exec upsert: Code: INVALID_ARGUMENT\ntarget: test.c0-.primary: vttablet: rpc error: code = InvalidArgument desc = Incorrect integer value: 'true' for column 'res' at row 1 (errno 1366) (sqlstate HY000) (CallerID: unsecure_grpc_client): Sql: \"insert into for_firebolt(city, id, `name`, adres, createdadd, floatingpoint, res) values (:vtg1, :_id_0, :vtg3, :vtg4, :vtg5, :vtg6, :vtg7) on duplicate key update adres = :vtg8, city = :vtg9, createdadd = :vtg10, floatingpoint = :vtg11, `name` = :vtg12, res = :vtg13\", BindVars: {_id_0: \"type:VARCHAR value:\\\"7002\\\"\"vtg1: \"type:VARCHAR value:\\\"Toronto\\\"\"vtg10: \"type:VARCHAR value:\\\"2022-11-10 21:00:00\\\"\"vtg11: \"type:VARCHAR value:\\\"22.1\\\"\"vtg12: \"type:VARCHAR value:\\\"Tommy\\\"\"vtg13: \"type:VARCHAR value:\\\"true\\\"\"vtg2: \"type:VARCHAR value:\\\"7002\\\"\"vtg3: \"type:VARCHAR value:\\\"Tommy\\\"\"vtg4: \"type:VARCHAR value:\\\"2\\\"\"vtg5: \"type:VARCHAR value:\\\"2022-11-10 21:00:00\\\"\"vtg6: \"type:VARCHAR value:\\\"22.1\\\"\"vtg7: \"type:VARCHAR value:\\\"true\\\"\"vtg8: \"type:VARCHAR value:\\\"2\\\"\"vtg9: \"type:VARCHAR value:\\\"Toronto\\\"\"}\n" component=plugin connector_id=451f7a85-9cd9-42e4-9954-48a6873b936f plugin_name=conduit-connector-vitess record_position=1664887965613-0
```

### Steps to reproduce

1. Create Pipeline
2. Create  Redis Source connector with "mode": "stream" and Vitess Destination connector (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:redis@v0.4.0-nightly.20221001  
        name: redis[stream]-source            
        settings:              
          redis.key: users
          redis.host: 172.17.0.3
          redis.port:
          redis.database:
          redis.username:
          redis.password:
          mode: stream
          pollingPeriod:
      con2:
        type: destination
        plugin: standalone:vitess
        name: vitess-destination
        settings:
           address: <hostname:port>
           table: test_table
           keyColumn: <column name >
           keyspace:  <specifies a VTGate keyspace>
           username:
           password:
           tabletType:
```
3. Start the pipeline
4. Get an error

```
2022-10-04T15:52:48+00:00 ERR error writing record error="insert record: exec upsert: Code: INVALID_ARGUMENT\ntarget: test.c0-.primary: vttablet: rpc error: code = InvalidArgument desc = Incorrect integer value: 'true' for column 'res' at row 1 (errno 1366) (sqlstate HY000) (CallerID: unsecure_grpc_client): Sql: \"insert into for_firebolt(city, id, `name`, adres, createdadd, floatingpoint, res) values (:vtg1, :_id_0, :vtg3, :vtg4, :vtg5, :vtg6, :vtg7) on duplicate key update adres = :vtg8, city = :vtg9, createdadd = :vtg10, floatingpoint = :vtg11, `name` = :vtg12, res = :vtg13\", BindVars: {_id_0: \"type:VARCHAR value:\\\"7002\\\"\"vtg1: \"type:VARCHAR value:\\\"Toronto\\\"\"vtg10: \"type:VARCHAR value:\\\"2022-11-10 21:00:00\\\"\"vtg11: \"type:VARCHAR value:\\\"22.1\\\"\"vtg12: \"type:VARCHAR value:\\\"Tommy\\\"\"vtg13: \"type:VARCHAR value:\\\"true\\\"\"vtg2: \"type:VARCHAR value:\\\"7002\\\"\"vtg3: \"type:VARCHAR value:\\\"Tommy\\\"\"vtg4: \"type:VARCHAR value:\\\"2\\\"\"vtg5: \"type:VARCHAR value:\\\"2022-11-10 21:00:00\\\"\"vtg6: \"type:VARCHAR value:\\\"22.1\\\"\"vtg7: \"type:VARCHAR value:\\\"true\\\"\"vtg8: \"type:VARCHAR value:\\\"2\\\"\"vtg9: \"type:VARCHAR value:\\\"Toronto\\\"\"}\n" component=plugin connector_id=451f7a85-9cd9-42e4-9954-48a6873b936f plugin_name=conduit-connector-vitess record_position=1664887965613-0
```

### Version

v0.3.0-nightly.20220927
