### ISSUE TITLE
An error occurs when trying to transfer data from the Redis source [mode: stream] to the Oracle Destination 

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-redis#24]
### Bug description

The user creates the Redis Sorce connector [mode: stream] and the Oracle Destination connector; then the user starts the pipeline -> the system returns an error

```
2022-10-04T16:04:51+00:00 ERR error writing record error="exec upsert \"MERGE INTO FOR_FIREBOLT USING DUAL ON (ID = :1) WHEN MATCHED THEN UPDATE SET ADRES=:2,CITY=:3,CREATEDADD=TO_DATE(:4, 'YYYY-MM-DD HH24:MI:SS'),FLOATINGPOINT=:5,NAME=:6,RES=:7 WHEN NOT MATCHED THEN INSERT (ADRES,CITY,CREATEDADD,FLOATINGPOINT,ID,NAME,RES) VALUES (:8,:9,TO_DATE(:10, 'YYYY-MM-DD HH24:MI:SS'),:11,:12,:13,:14)\", [7002 2 Toronto 2022-11-11 00:00:00 22.1 Tommy true 2 Toronto 2022-11-11 00:00:00 22.1 7002 Tommy true]: ORA-01722: invalid number" component=plugin connector_id=bc278b6d-717b-4b43-ac3d-ca0ff6aab3c0 plugin_name=conduit-connector-oracle record_position=1664887965613-0
```

### Steps to reproduce

1. Create the pipeline
2. Create Redis Source connector with "mode": "stream" and Vitess Destination connector (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:redis@v0.4.0-nightly.20221001  
        name: redis[stream]-source            
        settings:              
          redis.key: users
          redis.host: 172.17.0.3
          redis.port:
          redis.database:
          redis.username:
          redis.password:
          mode: stream
          pollingPeriod:
      con2:
        type: destination
        plugin: standalone:oracle
        name: Oracle-destination
        settings:
           url: <username/password@path:1521/my.domain.com> 
           table: test_table
           keyColumn: <column name >
3. Start the pipeline
4. Get an error

```
2022-10-04T16:04:51+00:00 ERR error writing record error="exec upsert \"MERGE INTO FOR_FIREBOLT USING DUAL ON (ID = :1) WHEN MATCHED THEN UPDATE SET ADRES=:2,CITY=:3,CREATEDADD=TO_DATE(:4, 'YYYY-MM-DD HH24:MI:SS'),FLOATINGPOINT=:5,NAME=:6,RES=:7 WHEN NOT MATCHED THEN INSERT (ADRES,CITY,CREATEDADD,FLOATINGPOINT,ID,NAME,RES) VALUES (:8,:9,TO_DATE(:10, 'YYYY-MM-DD HH24:MI:SS'),:11,:12,:13,:14)\", [7002 2 Toronto 2022-11-11 00:00:00 22.1 Tommy true 2 Toronto 2022-11-11 00:00:00 22.1 7002 Tommy true]: ORA-01722: invalid number" component=plugin connector_id=bc278b6d-717b-4b43-ac3d-ca0ff6aab3c0 plugin_name=conduit-connector-oracle record_position=1664887965613-0
```

### Version

v0.3.0-nightly.20220927
